name: Mutation Tests
on: push

jobs:
  mutation-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin
          cache: maven

      - name: Build
        run: mvn clean install -B

      - name: Run PiTest
        run: |
          mvn org.pitest:pitest-maven:mutationCoverage \
            -DoutputFormats=XML,HTML \
            -DargLine=""
        working-directory: ./core

      - name: Get mutation score
        run: |
          REPORT=./core/target/pit-reports/mutations.xml

          if [ ! -f "$REPORT" ]; then
            echo "❌ mutations.xml introuvable"
            exit 1
          fi

          TOTAL=$(grep -c "<mutation " "$REPORT")
          KILLED=$(grep -c "status='KILLED'" "$REPORT")

          if [ "$TOTAL" -eq 0 ]; then
            echo "❌ Aucun mutant trouvé."
            exit 1
          fi

          SCORE=$(echo "scale=2; ($KILLED * 100) / $TOTAL" | bc)
          echo "🎯 Mutation Score: $SCORE%"
